### ISSUE TITLE
fetchTicker() is no longer available since 1.9.207

### ISSUE THREAD

**Issue by mkutny** [ccxt-dev/ccxt#356]
```
> const ccxt = require('ccxt');
undefined
> const ex = new ccxt['bitfinex2'] ();
undefined
> ex.fetchTicker('BTC/USD')
TypeError: ex.fetchTicker is not a function
    at repl:1:4
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:440:10)
    at emitOne (events.js:120:20)
    at REPLServer.emit (events.js:210:7)
    at REPLServer.Interface._onLine (readline.js:282:10)
    at REPLServer.Interface._line (readline.js:631:8)
```

**Comment by kroitor** [comment]
Yep, looks like it's broken somehow. Looking into it now. Sorry for the inconvenience. Don't know how it managed to go through Travis.

**Comment by mkutny** [comment]
It looks like it does work when instantiating an exchange with parameters.

So if you authenticate then it works. And if you don't then public methods are not available.

If this is true then my wild guess is that you run your testcases after authentication.

**Comment by kroitor** [comment]
@mkutny thx for your help, the fixed build is on the way.

**Comment by kroitor** [comment]
Should work now as of 1.9.211+. Sorry again, missed it somehow. And thx once more for the notice. Hope to cover it all with tests asap.

**Comment by mkutny** [comment]
What a nasty bug )
Still present in 1.9.212.

**Comment by kroitor** [comment]
@mkutny are you sure? I can't repeat it anymore, thought I fixed it completely... Nope?

**Comment by kroitor** [comment]
No matter what I do with 1.9.212, can't repeat it. Though, I may be misinterpreting your answer, because the last few commits were not fixes, but more like tweaks, and it should actually work as of 1.9.211. Isn't it the case for you?

**Comment by mkutny** [comment]
It was fixed in 1.9.211.

But then reintroduced in a89a0a6.

Let me doublecheck.

**Comment by kroitor** [comment]
If you find a bug reappearing in 1.9.212, I'll surely revert back to 1.9.211, standing by for more info from you.

**Comment by mkutny** [comment]
Ok, let's see.

```
> :air:~/src/mm max$ yarn upgrade ccxt
yarn upgrade v1.2.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Rebuilding all packages...
success Saved lockfile.
success Saved 4 new dependencies.
├─ ccxt@1.9.212
├─ crypto-js@3.1.9-1
├─ node-fetch@2.0.0-alpha.8
└─ qs@6.5.0
✨  Done in 5.71s.
:air:~/src/mm max$ node
> const ccxt = require('ccxt')
undefined
> const bfx = new ccxt['bitfinex2'] ()
undefined
> bfx.fetchTicker()
TypeError: bfx.fetchTicker is not a function
    at repl:1:5
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:440:10)
    at emitOne (events.js:120:20)
    at REPLServer.emit (events.js:210:7)
    at REPLServer.Interface._onLine (readline.js:282:10)
    at REPLServer.Interface._line (readline.js:631:8)
> bfx
Exchange {
  hash: [Function: hash],
  hmac: [Function: hmac],
  jwt: [Function: jwt],
  binaryConcat: [Function: binaryConcat],
  stringToBinary: [Function: stringToBinary],
  stringToBase64: [Function: stringToBase64],
  base64ToBinary: [Function: base64ToBinary],
  base64ToString: [Function: base64ToString],
  binaryToString: [Function: binaryToString],
  utf16ToBase64: [Function: utf16ToBase64],
  encodeURIComponent: [Function: encodeURIComponent],
  urlencode: [Function: urlencode],
  rawencode: [Function: rawencode],
  omit: [Function: omit],
  pluck: [Function: pluck],
  unique: [Function: unique],
  extend: [Function: extend],
  deepExtend: [Function: deepExtend],
  flatten: [Function: flatten],
  groupBy: [Function: groupBy],
  indexBy: [Function: indexBy],
  sortBy: [Function: sortBy],
  keysort: [Function: keysort],
  decimal: [Function: decimal],
  safeFloat: [Function: safeFloat],
  safeString: [Function: safeString],
  safeInteger: [Function: safeInteger],
  safeValue: [Function: safeValue],
  capitalize: [Function: capitalize],
  json: [Function: stringify],
  unjson: [Function: parse],
  sum: [Function: sum],
  ordered: [Function: ordered],
  aggregate: [Function: aggregate],
  truncate: [Function: truncate],
  encode: [Function],
  decode: [Function],
  nodeVersion: '8.7.0',
  init: [Function],
  defineRestApi: [Function],
  executeRestRequest: [Function],
  fetch: [Function],
  fetch2: [Function],
  request: [Function],
  handleRestErrors: [Function],
  handleRestResponse: [Function],
  setMarkets: [Function],
  loadMarkets: [Function],
  fetchTickers: [Function],
  fetchOrder: [Function],
  fetchOrders: [Function],
  fetchOpenOrders: [Function],
  fetchClosedOrders: [Function],
  fetchMarkets: [Function],
  fetchOrderStatus: [AsyncFunction],
  account: [Function],
  commonCurrencyCode: [Function],
  market: [Function],
  marketId: [Function],
  market_id: [Function],
  marketIds: [Function],
  market_ids: [Function],
  symbol: [Function],
  extractParams: [Function],
  extract_params: [Function],
  implodeParams: [Function],
  implode_params: [Function],
  url: [Function],
  parseBidAsk: [Function],
  parseBidAsks: [Function],
  fetchL2OrderBook: [AsyncFunction],
  parseOrderBook: [Function],
  getCurrencyUsedOnOpenOrders: [Function],
  parseBalance: [Function],
  fetchPartialBalance: [AsyncFunction],
  fetchFreeBalance: [Function],
  fetchUsedBalance: [Function],
  fetchTotalBalance: [Function],
  parseTrades: [Function],
  parseOrders: [Function],
  filterOrdersBySymbol: [Function],
  parseOHLCV: [Function],
  parseOHLCVs: [Function],
  editLimitBuyOrder: [Function],
  editLimitSellOrder: [Function],
  editLimitOrder: [Function],
  editOrder: [AsyncFunction],
  createLimitBuyOrder: [Function],
  createLimitSellOrder: [Function],
  createMarketBuyOrder: [Function],
  createMarketSellOrder: [Function],
  costToPrecision: [Function],
  priceToPrecision: [Function],
  amountToPrecision: [Function],
  feeToPrecision: [Function],
  calculateFee: [Function],
  iso8601: [Function],
  parse8601: [Function],
  seconds: [Function],
  microseconds: [Function],
  milliseconds: [Function: now],
  nonce: [Function],
  id: undefined,
  enableRateLimit: false,
  rateLimit: 2000,
  timeout: 10000,
  verbose: false,
  userAgent: 
   { 'User-Agent': 'ccxt/1.9.212 (+https://github.com/ccxt-dev/ccxt) Node.js/8.7.0 (JavaScript)' },
  twofa: false,
  substituteCommonCurrencyCodes: true,
  timeframes: undefined,
  hasPublicAPI: true,
  hasPrivateAPI: true,
  hasCORS: false,
  hasFetchTicker: true,
  hasFetchOrderBook: true,
  hasFetchTrades: true,
  hasFetchTickers: false,
  hasFetchOHLCV: false,
  hasFetchBalance: true,
  hasFetchOrder: false,
  hasFetchOrders: false,
  hasFetchOpenOrders: false,
  hasFetchClosedOrders: false,
  hasFetchMyTrades: false,
  hasDeposit: false,
  hasWithdraw: false,
  hasCreateOrder: true,
  hasCancelOrder: true,
  balance: {},
  orderbooks: {},
  fees: {},
  orders: {},
  trades: {},
  last_http_response: undefined,
  last_json_response: undefined,
  Ymd: [Function],
  YmdHMS: [Function],
  proxy: '',
  fetch_balance: undefined,
  fetch_free_balance: [Function],
  fetch_used_balance: [Function],
  fetch_total_balance: [Function],
  fetch_l2_order_book: [AsyncFunction],
  fetch_order_book: undefined,
  fetch_tickers: [Function],
  fetch_ticker: undefined,
  fetch_trades: undefined,
  fetch_order: [Function],
  fetch_orders: [Function],
  fetch_open_orders: [Function],
  fetch_closed_orders: [Function],
  fetch_order_status: [AsyncFunction],
  fetch_markets: [Function],
  load_markets: [Function],
  set_markets: [Function],
  parse_balance: [Function],
  parse_bidask: [Function],
  parse_bidasks: [Function],
  parse_order_book: [Function],
  parse_trades: [Function],
  parse_orders: [Function],
  parse_ohlcv: [Function],
  parse_ohlcvs: [Function],
  edit_limit_buy_order: [Function],
  edit_limit_sell_order: [Function],
  edit_limit_order: [Function],
  edit_order: [AsyncFunction],
  create_limit_buy_order: [Function],
  create_limit_sell_order: [Function],
  create_market_buy_order: [Function],
  create_market_sell_order: [Function],
  create_order: undefined,
  calculate_fee: [Function],
  calculate_fee_rate: undefined,
  common_currency_code: [Function],
  price_to_precision: [Function],
  amount_to_precision: [Function],
  fee_to_precision: [Function],
  cost_to_precision: [Function] }
```

**Comment by kroitor** [comment]
Look like Yarn is wrong somehow... I just tried it with NPM and it worked :\
What I suggest is, maybe we retrigger the same to build 1.9.213 and see what's installed with yarn on your side. If it still does the same, I guess, I'll revert then. What do you think of it? I'm running a no-change build now ;)

**Comment by kroitor** [comment]
Actually, I don't want to bother you, so I'll revert to 1.9.211 anyway now.

**Comment by mkutny** [comment]
> Look like Yarn is wrong somehow... I just tried it with NPM and it worked :/

First I pulled 1.9.212 with git. The bug was there.
Only then I fell back to `yarn` - just in case I somehow messed with merging.

And finally, how about the next line from the output?

```
  userAgent: 
   { 'User-Agent': 'ccxt/1.9.212 (+https://github.com/ccxt-dev/ccxt) Node.js/8.7.0 (JavaScript)' },
```

> Actually, I don't want to bother you, so I'll revert to 1.9.211 anyway now.

Maybe you still pass some parameters to class during your test? Could you try the same three lines?
```
const ccxt = require('ccxt')
const bfx = new ccxt['bitfinex2'] ()
bfx.fetchTicker()
```

**Comment by mkutny** [comment]
Just made a fresh install into a clean directory with `npm`. The same.

I'm positive these three lines will fail in your setup as well.

**Comment by kroitor** [comment]
Restored back to the working version 1.9.211. Let me know if you have difficulties with it. Sorry once again. Best wishes.

**Comment by mkutny** [comment]
1.9.213 fixed the issue.

Thanks!
